/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef volatile unsigned int vuint32_t ;

#define RCC_BASE 0x40021000
#define RCC_CFGR *(vuint32_t*)(RCC_BASE + 0X04)
#define RCC_CR *(vuint32_t*)(RCC_BASE + 0X00)

#define set_bit(reg,bit) reg |= (1<<bit)
#define clear_bit(reg,bit) reg &= ~(1<<bit)

void clock_init1(void);
void clock_init2(void);
#define clock_num 2
int main(void)
{
	#if clock_num == 1
	clock_init1();
	#elif clock_num == 2
	clock_init2();
	#endif
    /* Loop forever */
	for(;;);
}

void clock_init1(void)
{
	/* 
	SW: System clock switch
	00: HSI selected as system clock
	*/
	clear_bit(RCC_CFGR,0);
	clear_bit(RCC_CFGR,1);
	/*
	 PPRE1: APB low-speed prescaler (APB1)
	 100: HCLK divided by 2
	*/
	set_bit(RCC_CFGR,10);
	clear_bit(RCC_CFGR,9);
	clear_bit(RCC_CFGR,8);
	/*
	 PPRE2: APB high-speed prescaler (APB2)
	 101: HCLK divided by 4
	*/
	set_bit(RCC_CFGR,13);
	clear_bit(RCC_CFGR,12);
	set_bit(RCC_CFGR,11);
}

void clock_init2(void)
{
	/*
	Bits 1:0 SW: System clock switch
	10: PLL selected as system clock
	*/
	set_bit(RCC_CFGR,1);
	clear_bit(RCC_CFGR,0);
	/*
	 PLLMUL: PLL multiplication factor
	 0110: PLL input clock x 8
	*/
	clear_bit(RCC_CFGR,21);
	set_bit(RCC_CFGR,20);
	set_bit(RCC_CFGR,19);
	clear_bit(RCC_CFGR,18);
	/*
	 PLLSRC: PLL entry clock source
	 0: HSI divided by 2 selected as PLL input clock
	*/
	clear_bit(RCC_CFGR,16);
	/*
	 PPRE1: APB low-speed prescaler (APB1)
	 100: HCLK divided by 2
	*/
	set_bit(RCC_CFGR,10);
	clear_bit(RCC_CFGR,9);
	clear_bit(RCC_CFGR,8);
	/*
	 PPRE2: APB high-speed prescaler (APB2)
	 101: HCLK divided by 4
	*/
	set_bit(RCC_CFGR,13);
	clear_bit(RCC_CFGR,12);
	set_bit(RCC_CFGR,11);
	/*
	in RCC_CR register
	Bit 24 PLLON: PLL enable
	1: PLL ON
	*/
	set_bit(RCC_CR,24);
}
