/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_gpio_driver.h"
//Function prototypes
void clock_init(void);
void gpio_init(void);

void _delay(uint32_t delay)
{
  for(uint32_t i=0;i<delay;i++)
  {
    for(uint32_t j=0;j<500;j++);
  }
}

int main(void)
{
  //Initialize clock
  clock_init();
  //Initialize GPIO
  gpio_init();
    /* Loop forever */
  while(1)
  {
    if(MCAL_GPIO_ReadPin(GPIOA,1) == 0)
    {
      MCAL_GPIO_TogglePin(GPIOB,1);
      while((MCAL_GPIO_ReadPin(GPIOA,1)) == 0);
    }
    if((MCAL_GPIO_ReadPin(GPIOA,13)) == 1)
    {
      MCAL_GPIO_TogglePin(GPIOB,13);
      _delay(5);
    }
    _delay(10);
  }
}

void clock_init(void)
{
  //Enable clock for GPIOA
	GPIOA_ClockEnable();
	GPIOB_ClockEnable();
}

void gpio_init(void)
{
  //set PB1 as output
  //MODE -> 01: Output mode, max speed 10 MHz
  //CNF -> 00: General purpose output push-pull
  PIN_CONFIG_t pin_conf;
  pin_conf.GPIO_PinNumber=1;
  pin_conf.GPIO_PinMode=Output_General_PushPull;
  pin_conf.GPIO_Direction=Output_10MHz;
  MCAL_GPIO_Init(GPIOB, &pin_conf);

  //set PB13 as output
  //MODE -> 01: Output mode, max speed 10 MHz
  //CNF -> 00: General purpose output push-pull
  pin_conf.GPIO_PinNumber=13;
  pin_conf.GPIO_PinMode=Output_General_PushPull;
  pin_conf.GPIO_Direction=Output_10MHz;
  MCAL_GPIO_Init(GPIOB, &pin_conf);

  //set PA1 as input
  //MODE -> 00: Input mode (reset state)
  //CNF -> 01: Floating input (reset state)
  pin_conf.GPIO_PinNumber=1;
  pin_conf.GPIO_PinMode=Floating;
  pin_conf.GPIO_Direction=Input;
  MCAL_GPIO_Init(GPIOA, &pin_conf);

  //set PA13 as input
  //MODE -> 00: Input mode (reset state)
  //CNF -> 01: Floating input (reset state)
  pin_conf.GPIO_PinNumber=13;
  pin_conf.GPIO_PinMode=Floating;
  pin_conf.GPIO_Direction=Input;
  MCAL_GPIO_Init(GPIOA, &pin_conf);
}
