/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "LCD.h"
#include"KEY_PAD.h"
#include "Segment_7.h"

void CLOCK_INIT(void)
{
  GPIOA_ClockEnable();
  GPIOB_ClockEnable();
}
void delay_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}
int main(void)
{
  // Initialize the clock
  CLOCK_INIT();
  // Initialize the LCD
  LCD_Init();
  delay_ms(10);
  // Display the string on the LCD
  LCD_SendString((const uint8_t *)"lcd is work");
  delay_ms(500);
  // Clear the LCD
  LCD_SendCommand(LCD_CLEAR_SCREEN);
  delay_ms(10);
  //initialize the keypad
  Keypad_init();
  LCD_SendString((const uint8_t *)"keypad is work");
  delay_ms(500);
  // Clear the LCD
  LCD_SendCommand(LCD_CLEAR_SCREEN);
  delay_ms(10);
  //initialize the segment 7
  segment_7_t seg1;
  seg1.pGPIOx = GPIOB;
  seg1.start_pin = GPIO_PIN_9;
  seg1.comman = COMMAN_ANODE;
  segment_7_init(&seg1);
  LCD_SendString((const uint8_t *)"7seg is work");
  delay_ms(500);
  // Clear the LCD
  LCD_SendCommand(LCD_CLEAR_SCREEN);

  uint8_t count = 0;
  while(1)
  {
    //wait for the key press
    uint8_t key = Keypad_getkey();
    //display the key on the LCD
    if(key != 0xff)
    {
      count++;
      LCD_Sendchar(key);
      segment_7_display(&seg1,key-'0');
    }
    if(count == 16)
    {
      LCD_SendCommand(LCD_BEGIN_AT_SECOND_ROW);
    }
    if (count >= 32)
    {
      LCD_SendCommand(LCD_BEGIN_AT_FIRST_ROW);
      count =0;
    }
  }
}
