/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//FOR STM32F103C6
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// GPIO address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

//RCC address
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)

//EXTERNAL INTERRUPT
#define EXTI_BASE 0x40010400
#define EXTI_IMR  *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR   *(volatile uint32_t *)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTIR1 *(volatile uint32_t *)(AFIO_BASE + 0x08)

//NVIC
#define NVIC_ISER0 *(volatile uint32_t *)(0xE000E100)

//MACROS
#define set_bit(reg,bit) reg |= (1<<bit)
#define clear_bit(reg,bit) reg &= ~(1<<bit)

int main(void)
{
  //ENABLE CLOCK FOR GPIOA
  set_bit(RCC_APB2ENR,0);
  set_bit(RCC_APB2ENR,2);

  //make PA0 INPUT
  set_bit(GPIOA_CRL,2);
  //MAKE PA13 OUTPUT
  GPIOA_CRH &= (0XFF0fFFFF);
  GPIOA_CRH |= (0X00200000);
  //configure PA0 as interrupt
  AFIO_EXTIR1=0;
  set_bit(EXTI_IMR,0);
  set_bit(EXTI_RTSR,0);
  //ENABLE INTERRUPT
  set_bit(NVIC_ISER0,6);

    /* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler(void)
{
  //TOGGLE LED
  GPIOA_ODR ^= (1<<13);
  //CLEAR PENDING BIT
  set_bit(EXTI_PR,0);
}
